"""Add work_days field to VacationRequest

Revision ID: 320c4ae89ebb
Revises: a8eb25a7e891
Create Date: 2024-12-19 19:24:34.815834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320c4ae89ebb'
down_revision = 'a8eb25a7e891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacation_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_days', sa.Float(), nullable=True))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacation_request', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('work_days')

    # ### end Alembic commands ###
